### ISSUE TITLE
spectra_gls_deconvolute broken in Windows with multi-core processing

### ISSUE THREAD

**Issue by egmayer3294** [leedrake5/CloudCal#6]
**Describe the bug**
When running multi-core processes with a Windows machine, spectra_gls_deconvolute is not successfully loading needed libraries or functions to clusters 

**To Reproduce**
1. Run spectra_gls_deconvolute on a windows machine without the single core fix from Deconvolution TryCatch commit on.
2. See the error

**Expected behavior**
Multi-core processing should work on Windows.

**Additional context**
I have solved the bug, here is the updated function tested on a windows machine. 

[spectra_gls_deconvolute_windows_multicore_fix.txt](https://github.com/leedrake5/CloudCal/files/8765912/spectra_gls_deconvolute_windows_multicore_fix.txt)

**Comment by leedrake5** [comment]
Opted for a try catch wrapper which reverts to single core if serialization fails and skipping deconvolution if xrftools installation fails.
