### ISSUE TITLE
rPDZ package not compatible with R 4.2.2 for windows

### ISSUE THREAD

**Issue by tyronerooney** [leedrake5/CloudCal#9]
**Describe the bug**
When trying to run read a PDZ file into CloudCal, the following error is reported:
"error:could not find function "readPDZ24""
When you attempt to install the rPDZ package locally or remotely the following error is received:

package ‘rPDZ’ successfully unpacked and MD5 sums checked
Error in unpackPkgZip(pkgs[i], pkgnames[i], lib, libs_only, lock, quiet) : 
  package ‘rPDZ’ not installed because it is not built for UCRT

Prognosis - from what appears with this error elsewhere, this appears to be related to an incompatibility between the current version of R and this package.  

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 109

**Additional context**

**Comment by leedrake5** [comment]
I've tried re-compiling a windows binary for rPDZ under R 4.2.2, let me know if you are still having problems.

**Comment by leedrake5** [comment]
Closing, will re-open if needed. You may need to run as administrator in Windows to install this package.
